---
title: "Ribbon & Spotted Seal Movement - A Data Package for R"
author:
  - name: Josh M. London
    orcid: 0000-0003-1689-0557
    email: josh.london@noaa.gov
    affiliations:
      - name: Alaska Fisheries Science Center, NOAA Fisheries
        address: 7600 Sand Point Way NE
        city: Seattle
        state: WA
        postal-code: 98115
format: gfm
---

## Summary

## Installation

The package can be installed in R with the following steps:
```{r}
#| eval: false
install.packages('pak')
pak::pak('noaa-afsc/HfPlMovement')
```


---

::: {.callout-note}
This repository is a scientific product and is not official communication of the National Oceanic and Atmospheric Administration, or the United States Department of Commerce. All NOAA GitHub project content is provided on an "as is" basis and the user assumes responsibility for its use. Any claims against the Department of Commerce or Department of Commerce bureaus stemming from the use of this GitHub project will be governed by all applicable Federal law. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce. The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government.
:::
